eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
server:
  port: 8087
spring:
  application:
    name: zuul
zuul:
  routes:
    api-a:
      path: /api-member/**
      service-id: member
    api-b:
      path: /api-feign/**
      service-id: feign